import type { Product } from "./cart-context"

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Noise-Cancelling Headphones",
    description: "Premium over-ear headphones with active noise cancellation and 30-hour battery life",
    price: 299.99,
    image: "/wireless-headphones.png",
    category: "Electronics",
    stock: 45,
    rating: 4.8,
    reviews: 1234,
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Track your health and fitness with GPS, heart rate monitoring, and sleep tracking",
    price: 249.99,
    image: "/fitness-smartwatch.png",
    category: "Electronics",
    stock: 78,
    rating: 4.6,
    reviews: 892,
  },
  {
    id: "3",
    name: "Mechanical Gaming Keyboard",
    description: "RGB backlit mechanical keyboard with customizable keys and macro support",
    price: 159.99,
    image: "/gaming-keyboard.png",
    category: "Electronics",
    stock: 32,
    rating: 4.7,
    reviews: 567,
  },
  {
    id: "4",
    name: "4K Webcam",
    description: "Professional 4K webcam with auto-focus and built-in noise-cancelling microphone",
    price: 129.99,
    image: "/4k-webcam.png",
    category: "Electronics",
    stock: 56,
    rating: 4.5,
    reviews: 423,
  },
  {
    id: "5",
    name: "Ergonomic Office Chair",
    description: "Premium mesh office chair with lumbar support and adjustable armrests",
    price: 399.99,
    image: "/ergonomic-office-chair.png",
    category: "Furniture",
    stock: 23,
    rating: 4.9,
    reviews: 789,
  },
  {
    id: "6",
    name: "Standing Desk Converter",
    description: "Adjustable standing desk converter with dual monitor support",
    price: 279.99,
    image: "/standing-desk-setup.png",
    category: "Furniture",
    stock: 18,
    rating: 4.6,
    reviews: 345,
  },
  {
    id: "7",
    name: "Portable SSD 2TB",
    description: "Ultra-fast portable SSD with USB-C connectivity and hardware encryption",
    price: 189.99,
    image: "/portable-ssd.jpg",
    category: "Electronics",
    stock: 67,
    rating: 4.8,
    reviews: 912,
  },
  {
    id: "8",
    name: "Wireless Charging Pad",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices",
    price: 39.99,
    image: "/wireless-charger.png",
    category: "Electronics",
    stock: 145,
    rating: 4.4,
    reviews: 678,
  },
  {
    id: "9",
    name: "LED Desk Lamp",
    description: "Smart LED desk lamp with adjustable brightness and color temperature",
    price: 79.99,
    image: "/modern-desk-lamp.png",
    category: "Furniture",
    stock: 89,
    rating: 4.7,
    reviews: 456,
  },
  {
    id: "10",
    name: "Laptop Stand",
    description: "Aluminum laptop stand with adjustable height and cable management",
    price: 49.99,
    image: "/laptop-stand.png",
    category: "Furniture",
    stock: 112,
    rating: 4.5,
    reviews: 234,
  },
  {
    id: "11",
    name: "USB-C Hub",
    description: "7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader, and power delivery",
    price: 59.99,
    image: "/usb-hub.png",
    category: "Electronics",
    stock: 98,
    rating: 4.6,
    reviews: 567,
  },
  {
    id: "12",
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with precision tracking and long battery life",
    price: 34.99,
    image: "/wireless-mouse.png",
    category: "Electronics",
    stock: 156,
    rating: 4.5,
    reviews: 890,
  },
]

export const categories = [
  { id: "all", name: "All Products", count: products.length },
  { id: "electronics", name: "Electronics", count: products.filter((p) => p.category === "Electronics").length },
  { id: "furniture", name: "Furniture", count: products.filter((p) => p.category === "Furniture").length },
]
